'use server';
/**
 * @fileOverview This file provides a Genkit flow for generating a daily market brief and FII/DII insights.
 *
 * - getAIMarketBriefAndFIIDIIInsights - A function that generates the market brief and FII/DII insights.
 * - AIMarketBriefAndFIIDIIInsightsInput - The input type for the getAIMarketBriefAndFIIDIIInsights function.
 * - AIMarketBriefAndFIIDIIInsightsOutput - The return type for the getAIMarketBriefAndFIIDIIInsights function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const AIMarketBriefAndFIIDIIInsightsInputSchema = z.object({
  currentTime: z.string().describe('Current time, e.g., "8:45 AM"'),
  sgxNiftyChangePercent: z.number().describe('Percentage change in SGX Nifty (e.g., 0.3).'),
  sgxNiftyPredictedPoints: z.number().describe('Predicted Nifty opening points based on SGX Nifty.'),
  fiiNetCashCr: z.number().describe('FII net cash buying/selling in Crores (e.g., 1240).'),
  fiiDiiNetCr: z.number().describe('DII net cash buying/selling in Crores (e.g., -380.20).'),
  mfFlowsCr: z.number().describe('Mutual fund flows in Crores (e.g., 650).'),
  fiiFuturesLongPercent: z.number().describe('FII index futures long percentage (e.g., 78).'),
  fiiConsecutiveBuyingDays: z.number().describe('Number of consecutive FII buying days (e.g., 5).'),
  niftyHistoricalGainAfterFIIStreakPercent: z.number().describe('Historical Nifty gain percentage after such FII buying streaks (e.g., 4.2).'),
  niftyHistoricalGainProbabilityAfterFIIStreakPercent: z.number().describe('Probability of Nifty gaining after such FII buying streaks (e.g., 78).'),
  sectorFocus: z.string().describe('String describing sectors receiving maximum FII accumulation (e.g., "Banking and Auto").'),
  keyEvents: z.array(z.string()).describe('List of important market events for the day.'),
  aiPicks: z.array(z.string()).describe('List of AI stock picks with their rationale (e.g., "RELIANCE (breakout)").'),
  niftySupport: z.number().describe('Nifty support level.'),
  niftyResistance: z.number().describe('Nifty resistance level.'),
  niftyRecommendedFnoStrategy: z.string().describe('Recommended F&O strategy for Nifty (e.g., "22,450 CE").'),
  indiaVixValue: z.number().describe('India VIX value (e.g., 13.4).'),
  vixOutlook: z.string().describe('Interpretation of VIX value (e.g., "favorable for option buying today").')
});
export type AIMarketBriefAndFIIDIIInsightsInput = z.infer<typeof AIMarketBriefAndFIIDIIInsightsInputSchema>;

const AIMarketBriefAndFIIDIIInsightsOutputSchema = z.object({
  marketDirection: z.string().describe('Expected Nifty opening, e.g., "NIFTY likely to open +45 pts (SGX +0.3%)". Extract this directly from the full narrative.'),
  fiiDiiSummary: z.string().describe('Summary of FII/DII activity, including net cash, futures positions, consecutive buying days, historical impact, and sector focus. Clearly state institutional conviction and expected Nifty bias. Extract this directly from the full narrative.'),
  keyEventsSummary: z.array(z.string()).describe('List of important market events for the day. Extract this directly from the full narrative.'),
  aiPicksSummary: z.array(z.string()).describe('List of AI stock recommendations. Extract this directly from the full narrative.'),
  fnoOutlook: z.string().describe('F&O specific insights, including Nifty range and recommended strategy. Extract this directly from the full narrative.'),
  riskNote: z.string().describe('General market risk note based on VIX. Extract this directly from the full narrative.'),
  niftyBiasRating: z.string().describe('Overall Nifty bias rating (e.g., "VERY BULLISH", "MILDLY BULLISH", "NEUTRAL", "MILDLY BEARISH", "VERY BEARISH"). Extract this directly from the full narrative.'),
  fullNarrative: z.string().describe('The complete narrative market brief and FII/DII interpretation generated by the AI.')
});
export type AIMarketBriefAndFIIDIIInsightsOutput = z.infer<typeof AIMarketBriefAndFIIDIIInsightsOutputSchema>;

export async function getAIMarketBriefAndFIIDIIInsights(input: AIMarketBriefAndFIIDIIInsightsInput): Promise<AIMarketBriefAndFIIDIIInsightsOutput> {
  return aiMarketBriefAndFIIDIIInsightsFlow(input);
}

const aiMarketBriefAndFIIDIIInsightsPrompt = ai.definePrompt({
  name: 'aiMarketBriefAndFIIDIIInsightsPrompt',
  input: { schema: AIMarketBriefAndFIIDIIInsightsInputSchema },
  output: { schema: AIMarketBriefAndFIIDIIInsightsOutputSchema },
  prompt: `You are an expert financial analyst and AI trading coach for "TheDigiOcean", India's premier AI trading platform.
Your task is to generate a concise daily morning market brief and a detailed narrative interpretation of FII/DII cash and derivatives data.

Generate the brief based on the following real-time data:

Current Time: {{{currentTime}}}

**Market Opening & SGX Nifty:**
  - SGX Nifty Change: {{sgxNiftyChangePercent}}%
  - Predicted Nifty Open Points: {{sgxNiftyPredictedPoints}}

**FII/DII Activity:**
  - FII Net Cash: ₹{{fiiNetCashCr}} Cr
  - DII Net Cash: ₹{{fiiDiiNetCr}} Cr
  - MF Flows: ₹{{mfFlowsCr}} Cr
  - FII Index Futures Long Position: {{fiiFuturesLongPercent}}%
  - Consecutive FII Buying Days: {{fiiConsecutiveBuyingDays}}
  - Historical Nifty Gain After FII Streak: {{niftyHistoricalGainAfterFIIStreakPercent}}% (Probability: {{niftyHistoricalGainProbabilityAfterFIIStreakPercent}}%)
  - Sector Focus for FIIs: {{sectorFocus}}

**Key Market Events Today:**
{{#each keyEvents}}
  - {{{this}}}
{{/each}}

**AI Stock Picks:**
{{#each aiPicks}}
  - {{{this}}}
{{/each}}

**Nifty F&O Outlook:**
  - Nifty Support: {{niftySupport}}
  - Nifty Resistance: {{niftyResistance}}
  - Recommended F&O Strategy: {{niftyRecommendedFnoStrategy}}

**India VIX & Risk Note:**
  - India VIX Value: {{indiaVixValue}}
  - VIX Outlook: {{vixOutlook}}

---

As the AI trading coach, compile a comprehensive, easy-to-understand morning brief for TheDigiOcean users. The brief should flow naturally and cover all aspects provided in the input data.

**Start the brief with the expected Nifty opening based on SGX Nifty.**
**Next, provide a detailed analysis of FII/DII activity.** Interpret their net cash flows, futures positioning, and any notable streaks. Explain the historical implications of such FII behavior and highlight their sector focus. Conclude this section by clearly stating the overall institutional conviction and expected Nifty bias.
**Then, list any important key market events for the day.**
**Follow with TheDigiOcean's AI stock picks.**
**Provide an F&O outlook for Nifty**, including key support and resistance levels and the recommended F&O strategy.
**Finally, include a concise risk note** based on the current India VIX value and its interpretation.
**Conclude the entire brief with a clear, overall Nifty bias rating** using one of these: "VERY BULLISH", "MILDLY BULLISH", "NEUTRAL", "MILDLY BEARISH", "VERY BEARISH".

The generated response will be used to populate the fields of the output schema. Ensure the 'fullNarrative' contains the entire coherent text of your brief. The other structured fields should be direct extractions from this narrative according to their descriptions.`
});

const aiMarketBriefAndFIIDIIInsightsFlow = ai.defineFlow(
  {
    name: 'aiMarketBriefAndFIIDIIInsightsFlow',
    inputSchema: AIMarketBriefAndFIIDIIInsightsInputSchema,
    outputSchema: AIMarketBriefAndFIIDIIInsightsOutputSchema,
  },
  async (input) => {
    const { output } = await aiMarketBriefAndFIIDIIInsightsPrompt(input);
    return output!;
  }
);