"use client";

import React, { useState } from 'react';
import { 
  Boxes, 
  Zap, 
  Settings2, 
  Cpu, 
  Layers, 
  Activity, 
  ShieldCheck, 
  Play, 
  Save, 
  RefreshCcw,
  BarChart3,
  Bot,
  Scale,
  Radar,
  Network,
  ChevronRight,
  Info
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Progress } from "@/components/ui/progress";
import { Input } from "@/components/ui/input";
import { MascotDigi } from "@/components/mascot-digi";
import { cn } from "@/lib/utils";
import { 
  useFirebase, 
  useUser, 
  addDocumentNonBlocking 
} from '@/firebase';
import { collection } from 'firebase/firestore';
import { orchestrateAlgoAgents, type AlgoOrchestratorOutput } from '@/ai/flows/algo-orchestrator-flow';

const SPECIALIZED_AGENTS = [
  { 
    id: 'vol-surface', 
    name: 'Volatility Surface Model', 
    description: 'Analyzes IV Skew and surface shifts for option pricing anomalies.',
    icon: Radar,
    color: 'text-blue-500'
  },
  { 
    id: 'gamma-map', 
    name: 'Gamma Exposure Mapper', 
    description: 'Tracks GEX levels to identify pinning points and volatility triggers.',
    icon: Activity,
    color: 'text-purple-500'
  },
  { 
    id: 'lstm-pred', 
    name: 'Transformer Predictor', 
    description: 'Deep-learning time-series forecasting for short-term price motion.',
    icon: Network,
    color: 'text-indigo-500'
  },
  { 
    id: 'rl-exec', 
    name: 'RL Order Executor', 
    description: 'Optimal entry/routing using Reinforcement Learning to minimize slippage.',
    icon: Zap,
    color: 'text-gold'
  },
  { 
    id: 'prob-exit', 
    name: 'Probabilistic Exit Engine', 
    description: 'Dynamic SL/TP calculated from real-time win-probability decay.',
    icon: ShieldCheck,
    color: 'text-bull'
  },
];

export default function AlgoBuilderPage() {
  const { firestore } = useFirebase();
  const { user } = useUser();
  const userId = user?.uid;

  const [activeAgents, setActiveAgents] = useState<string[]>(['vol-surface', 'gamma-map', 'lstm-pred']);
  const [style, setStyle] = useState<'Scalper' | 'Trend Rider' | 'Institutional'>('Trend Rider');
  const [isAssembling, setIsAssembling] = useState(false);
  const [orchestration, setOrchestration] = useState<AlgoOrchestratorOutput | null>(null);

  const toggleAgent = (id: string) => {
    setActiveAgents(prev => 
      prev.includes(id) ? prev.filter(a => a !== id) : [...prev, id]
    );
  };

  const handleRunOrchestration = async () => {
    if (activeAgents.length === 0) return;
    setIsAssembling(true);
    try {
      const result = await orchestrateAlgoAgents({
        symbol: 'NIFTY',
        tradingStyle: style,
        enabledAgents: activeAgents.map(id => SPECIALIZED_AGENTS.find(a => a.id === id)?.name || id)
      });
      setOrchestration(result);
    } catch (error) {
      console.error("Orchestrator Error:", error);
    } finally {
      setIsAssembling(false);
    }
  };

  const handleDeployAlgo = () => {
    if (!firestore || !userId || !orchestration) return;
    
    const algosRef = collection(firestore, 'users', userId, 'algos');
    addDocumentNonBlocking(algosRef, {
      userId,
      name: `Multi-Agent ${style} Bot`,
      status: 'Deployed',
      mode: 'Live',
      brokerId: 'default',
      capitalAllocated: 100000,
      riskConfig: JSON.stringify(orchestration.riskParameters),
      code: "# Generated by Digi Orchestrator\nimport digi_sdk as digi\n# Multi-agent execution logic initialized",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    });
  };

  return (
    <div className="space-y-6 pb-10">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-card border p-6 rounded-2xl shadow-sm">
        <div className="flex items-center gap-4">
          <div className="p-3 rounded-xl bg-primary/10 text-primary">
            <Boxes className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-2xl font-headline font-bold">AI Multi-Agent Algo Builder</h1>
            <p className="text-xs text-muted-foreground font-medium uppercase tracking-wider flex items-center gap-2">
              <Network className="w-3.5 h-3.5 text-primary" />
              Advanced Orchestration Architecture
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button variant="outline" className="gap-2 h-10 font-bold" onClick={() => setOrchestration(null)}>
            <RefreshCcw className="w-4 h-4" />
            RESET ASSEMBLY
          </Button>
          <Button 
            className="gap-2 h-10 font-bold shadow-purple" 
            onClick={handleRunOrchestration}
            disabled={isAssembling || activeAgents.length === 0}
          >
            {isAssembling ? <Zap className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4 fill-current" />}
            {isAssembling ? "Assembling Core..." : "START ORCHESTRATION"}
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Agent Selection */}
        <div className="lg:col-span-4 space-y-6">
          <Card className="border-none shadow-sm">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-bold uppercase tracking-widest flex items-center gap-2">
                <Cpu className="w-4 h-4 text-primary" />
                Specialized Algo Agents
              </CardTitle>
              <CardDescription className="text-[10px] uppercase font-bold">Select components for your hive-mind</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3 pt-2">
              {SPECIALIZED_AGENTS.map((agent) => (
                <div 
                  key={agent.id} 
                  className={cn(
                    "flex flex-col p-4 rounded-xl border transition-all cursor-pointer group",
                    activeAgents.includes(agent.id) 
                      ? "bg-primary/5 border-primary/20 shadow-sm" 
                      : "bg-background border-border hover:border-primary/10"
                  )}
                  onClick={() => toggleAgent(agent.id)}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div className={cn("p-2 rounded-lg bg-white shadow-sm", agent.color)}>
                        <agent.icon className="w-4 h-4" />
                      </div>
                      <span className="text-xs font-bold">{agent.name}</span>
                    </div>
                    <Switch checked={activeAgents.includes(agent.id)} />
                  </div>
                  <p className="text-[10px] text-muted-foreground mt-2 leading-relaxed">
                    {agent.description}
                  </p>
                </div>
              ))}
            </CardContent>
          </Card>

          <Card className="border-none shadow-sm bg-gradient-to-br from-primary/5 to-transparent">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-bold uppercase tracking-widest text-primary flex items-center gap-2">
                <Scale className="w-4 h-4" />
                Execution Profile
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              {['Scalper', 'Trend Rider', 'Institutional'].map((s) => (
                <button
                  key={s}
                  onClick={() => setStyle(s as any)}
                  className={cn(
                    "w-full text-left p-3 rounded-xl text-xs font-bold transition-all border",
                    style === s 
                      ? "bg-primary text-white border-primary shadow-purple" 
                      : "bg-white text-muted-foreground border-border hover:bg-muted/50"
                  )}
                >
                  {s.toUpperCase()}
                </button>
              ))}
            </CardContent>
          </Card>
        </div>

        {/* Right: Orchestration & Simulation */}
        <div className="lg:col-span-8 space-y-6">
          {!orchestration ? (
            <Card className="h-[600px] flex flex-col items-center justify-center text-center p-10 bg-muted/10 border-none">
              <MascotDigi expression="Thinking" size="lg" />
              <div className="max-w-md mt-6 space-y-4">
                <h2 className="text-2xl font-bold italic text-primary">"The Multi-Agent Hive-Mind"</h2>
                <p className="text-sm text-muted-foreground">
                  Select your specialized agents and execution style. Digi will then orchestrate their outputs, calculate confidence weights, and generate a dynamic risk-adaptive execution plan.
                </p>
                <div className="flex justify-center gap-4 pt-4">
                  <div className="p-3 bg-white rounded-xl border flex items-center gap-2">
                    <Bot className="w-4 h-4 text-primary" />
                    <span className="text-[10px] font-bold uppercase">Meta-AI Managed</span>
                  </div>
                  <div className="p-3 bg-white rounded-xl border flex items-center gap-2">
                    <ShieldCheck className="w-4 h-4 text-bull" />
                    <span className="text-[10px] font-bold uppercase">Risk Adaptive</span>
                  </div>
                </div>
              </div>
            </Card>
          ) : (
            <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
              
              {/* Meta-AI Verdict */}
              <Card className="border-none shadow-sm overflow-hidden bg-primary shadow-purple">
                <CardHeader className="bg-white/10 text-white border-b border-white/10">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Bot className="w-5 h-5 fill-current" />
                      <CardTitle className="text-lg font-bold">Meta-AI Orchestration Summary</CardTitle>
                    </div>
                    <Badge variant="outline" className="text-white border-white/20">LIVE AGGREGATION</Badge>
                  </div>
                </CardHeader>
                <CardContent className="p-6 text-white space-y-6">
                  <div className="flex flex-col md:flex-row gap-8 items-center">
                    <div className="flex flex-col items-center gap-2 min-w-[140px]">
                      <p className="text-[10px] font-bold uppercase opacity-70">Consensus Bias</p>
                      <div className={cn(
                        "text-4xl font-black tracking-tighter",
                        orchestration.consensus.direction === 'BUY' ? "text-white" : "text-white/80"
                      )}>
                        {orchestration.consensus.direction}
                      </div>
                      <div className="text-xs font-bold bg-white/20 px-3 py-1 rounded-full">
                        {orchestration.consensus.aggregatedScore}% CONFIDENCE
                      </div>
                    </div>
                    <div className="flex-1 space-y-3">
                      <p className="text-sm font-medium leading-relaxed italic">
                        "{orchestration.consensus.reasoning}"
                      </p>
                      <div className="flex gap-2">
                        {activeAgents.map(id => (
                          <Badge key={id} className="bg-white/10 text-white border-none text-[8px]">
                            {SPECIALIZED_AGENTS.find(a => a.id === id)?.name}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Agent Confidence Heatmap */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <Card className="border-none shadow-sm">
                  <CardHeader>
                    <CardTitle className="text-sm font-bold uppercase tracking-widest flex items-center gap-2">
                      <BarChart3 className="w-4 h-4 text-primary" />
                      Agent Signal Matrix
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {orchestration.agentBreakdown.map((agent, i) => (
                      <div key={i} className="space-y-2 p-3 bg-muted/20 rounded-xl">
                        <div className="flex justify-between items-center text-[10px] font-bold">
                          <span className="text-muted-foreground uppercase">{agent.agentName}</span>
                          <span className={cn(
                            agent.bias === 'BULLISH' ? "text-bull" : agent.bias === 'BEARISH' ? "text-bear" : "text-gold"
                          )}>{agent.bias} ({agent.confidence}%)</span>
                        </div>
                        <Progress value={agent.confidence} className="h-1" />
                        <p className="text-[9px] text-muted-foreground italic">"{agent.keySignal}"</p>
                      </div>
                    ))}
                  </CardContent>
                </Card>

                {/* Risk-Adaptive Execution Plan */}
                <Card className="border-none shadow-sm border-l-4 border-l-bull bg-bull/[0.02]">
                  <CardHeader>
                    <CardTitle className="text-sm font-bold uppercase tracking-widest flex items-center gap-2 text-bull">
                      <ShieldCheck className="w-4 h-4" />
                      Risk-Adaptive Parameters
                    </CardTitle>
                    <CardDescription className="text-[10px] font-bold">Generated for {style} style</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-6">
                    <div className="grid grid-cols-2 gap-4">
                      <div className="p-3 bg-white rounded-xl border border-bull/10">
                        <p className="text-[9px] font-bold text-muted-foreground uppercase">Adaptive Lot Size</p>
                        <p className="text-lg font-extrabold mono-font text-bull">{orchestration.riskParameters.suggestedLotSize}</p>
                      </div>
                      <div className="p-3 bg-white rounded-xl border border-bull/10">
                        <p className="text-[9px] font-bold text-muted-foreground uppercase">Risk Multiplier</p>
                        <p className="text-lg font-extrabold mono-font text-gold">{orchestration.riskParameters.adaptiveRiskMultiplier}x</p>
                      </div>
                    </div>
                    
                    <div className="space-y-2">
                      <div className="flex justify-between text-[10px] font-bold">
                        <span className="text-muted-foreground">STOP-LOSS ZONE</span>
                        <span className="text-bear">{orchestration.riskParameters.stopLossZone}</span>
                      </div>
                      <div className="flex justify-between text-[10px] font-bold">
                        <span className="text-muted-foreground">PRIMARY TARGET</span>
                        <span className="text-bull">{orchestration.riskParameters.targetZone}</span>
                      </div>
                    </div>

                    <Button 
                      className="w-full h-12 font-bold shadow-purple bg-bull hover:bg-bull/90 gap-2"
                      onClick={handleDeployAlgo}
                    >
                      <Play className="w-4 h-4 fill-current" />
                      DEPLOY LIVE TO BROKER
                    </Button>
                  </CardContent>
                </Card>
              </div>

              {/* Technical Architecture Note */}
              <div className="p-4 bg-muted/30 rounded-2xl border border-dashed flex items-start gap-4">
                <div className="p-2 bg-background rounded-lg text-primary">
                  <Info className="w-4 h-4" />
                </div>
                <div className="space-y-1">
                  <p className="text-[10px] font-bold uppercase tracking-widest text-primary">Hive-Mind Architecture Note</p>
                  <p className="text-[11px] text-muted-foreground leading-relaxed">
                    This orchestration utilizes a **weighted-voting ensemble**. The Transformer Predictor provides the directional prior, while the Volatility Surface and GEX agents calibrate the conviction based on market liquidity and options pinning. The RL Executor finalizes the trade only when the "bid-ask spread efficiency" is at its daily peak.
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
